#variables

NAME = libft.a

SRCDIR = ./src/

INCDIR = ../../inc/

FILES = ft_isalpha\
		ft_isdigit\
		ft_isalnum\
		ft_isascii\
		ft_isprint\
		ft_strlen\
		ft_memset\
		ft_bzero\
		ft_memcpy\
		ft_memmove\
		ft_strlcpy\
		ft_strlcat\
		ft_toupper\
		ft_tolower\
		ft_strchr\
		ft_strrchr\
		ft_strncmp\
		ft_memchr\
		ft_memcmp\
		ft_strnstr\
		ft_atoi\
		ft_calloc\
		ft_strdup\
		ft_substr\
		ft_strjoin\
		ft_strtrim\
		ft_split\
		ft_itoa\
		ft_strmapi\
		ft_striteri\
		ft_putchar_fd\
		ft_putstr_fd\
		ft_putendl_fd\
		ft_putnbr_fd\

SRC = $(addprefix $(SRCDIR), $(addsuffix .c, $(FILES)))

INC = $(addprefix $(INCDIR), libft.h)

OBJ = $(SRC:.c=.o)

CC = cc

CFLAGS = -Wall -Wextra -Werror -g

#rules

all: $(NAME)

$(NAME): $(OBJ)
	ar rcs $(INCDIR)$(NAME) $(OBJ)

%.o: %.c
	$(CC) -I$(INCDIR) $(CFLAGS) -c $< -o $@

clean: 
	rm -f $(OBJ)

fclean: clean
	rm -f $(INCDIR)$(NAME)

re: fclean all

.PHONY: clean fclean re all
